### ISSUE TITLE
Error open reports from JasperReports

### ISSUE THREAD

**Issue by eaguigar** [daust/JasperReportsIntegration#130]
We are migrating from on-premise to OCI, but some reports are show us the next error:

SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [ReportWrapper] in context with path [/JasperReportsIntegration] threw exception
        java.lang.RuntimeException: Error executing SQL statement for: report name.
                at de.oc.utils.Utils.throwRuntimeException(Unknown Source)
                at de.oc.integration.jasper.webapp.ReportWrapper.service(Unknown Source)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)

The Jasper Reports Integration version is 2.4 with Tomcat 9.0 and Oracle EE 19c. with APEX 20.1.

The same products and versions are working in on premise.

Can you help us ?

Regards

**Comment by daust** [comment]
```
java.lang.RuntimeException: Error executing SQL statement for: report name.
```
There seems to be an error with the SQL statement. 
Did you try just running the report query as the schema you are connecting with on the new target database? Perhaps there are still objects missing?

**Comment by eaguigar** [comment]
Thanks for your anwser.

Yes, we tested the query directly in the Database ande the query run without a problema, also, we tested the same report from Netbeans with Jasper API and the result is we are expected, but from JRI with Tomcat is show us the error.

Any suggestion ?

Regards
